Repository mudita/mudita-center, pull requests merged in 2024-05, with the labels that each got.

#1869 [CP-2813] Stress test - sometimes "Unfortunately, synchronization failed" error appears and passcode modal appears for a second
  libs/core/device-initialization/actions/initialize-mudita-pure.action.ts
  libs/core/device/actions/get-unlock-status.action.ts
  libs/core/device/reducers/device.reducer.ts
Labels: QA

#1868 [CP-2817] Empty settings page after unsuccessful force update on 0.0.1-qa-2.3.0-rc3
  libs/core/analytic-data-tracker/services/analytic-data-tracker.service.ts
Labels: QA

#1872 [CP-2821] Outdated Copyright on macOS
  LICENSE.md
  apps/mudita-center/package.json
Labels: QA

#1876 [CP-2830] Grey highlight is faster than the scroll tool on the right side of the contact search list
  libs/core/__deprecated__/renderer/components/core/input-search/input-search.component.tsx
Labels: QA

#1866 [CP-2802] Incorrect MDS UI Implementation in Devices Drawer
  libs/core/__deprecated__/renderer/components/core/modal/modal.styled.elements.tsx
  libs/core/device-select/components/device-select-drawer.component.tsx
  libs/core/device-select/components/drawer-device.component.tsx
Labels: QA

#1887 [CP-2872] Move autoupdater from core to electron/application-updater
  apps/mudita-center/src/main.ts
  libs/core/__deprecated__/main/autoupdate.ts
  libs/core/__deprecated__/main/functions/register-avaible-app-update-listener.ts
  libs/core/__deprecated__/main/functions/register-downloaded-app-update-listener.ts
  libs/core/__deprecated__/main/functions/register-error-app-update-listener.ts
  libs/core/__deprecated__/main/functions/register-not-avaible-app-update-listener.ts
  libs/core/__deprecated__/renderer/requests/check-app-update.request.ts
  libs/core/__deprecated__/renderer/requests/download-app-update.request.ts
  libs/core/__deprecated__/renderer/requests/install-app-update.request.ts
  libs/core/__deprecated__/renderer/wrappers/app-update-step-modal/app-update-step-modal.component.test.tsx
  libs/core/__deprecated__/renderer/wrappers/app-update-step-modal/app-update-step-modal.component.tsx
  libs/core/core/application.module.ts
  libs/core/core/hooks/use-application-update-effects.ts
  libs/core/settings/actions/check-update-available.action.ts
  libs/electron/application-updater/src/index.ts
  libs/electron/application-updater/src/lib/application-updater.controller.ts
  libs/electron/application-updater/src/lib/application-updater.module.ts
  libs/electron/application-updater/src/lib/application-updater.requests.ts
  libs/electron/application-updater/src/lib/application-updater.service.ts
  libs/electron/application-updater/src/lib/base-application-updater.service.ts
  libs/electron/application-updater/src/lib/ipc-application-updater.event.ts
  libs/electron/application-updater/src/lib/mock-application-updater.service.ts
  libs/shared/utils/src/lib/call-renderer.helper.ts
Labels: enhancement

#1888 [CP-2873] Implement autoupdater mock for e2e
  libs/core/__deprecated__/renderer/components/core/network-status-checker/network-status-checker.component.tsx
  libs/core/__deprecated__/renderer/components/core/network-status-checker/network-status-checker.container.tsx
  libs/core/__deprecated__/renderer/models/models.ts
  libs/core/__deprecated__/renderer/models/network-status/network-status.test.ts
  libs/core/__deprecated__/renderer/models/network-status/network-status.ts
  libs/core/__deprecated__/renderer/utils/hooks/use-help-search/use-help-search.test.ts
  libs/core/__deprecated__/renderer/utils/hooks/use-help-search/use-help-search.ts
  libs/core/core/application.module.ts
  libs/core/core/components/apps/base-app/base-app.component.tsx
  libs/core/news/actions/load-news/load-news.action.test.ts
  libs/core/news/actions/load-news/load-news.action.ts
  libs/core/settings/hooks/use-online-checker.ts
  libs/electron/application-updater/src/lib/application-updater.module.ts
  libs/electron/application-updater/src/lib/mock-application-updater.service.ts
  libs/shared/app-state/src/index.ts
  libs/shared/app-state/src/lib/action-name.ts
  libs/shared/app-state/src/lib/app-state.reducer.ts
  libs/shared/app-state/src/lib/online-status/base.action.ts
  libs/shared/app-state/src/lib/online-status/online-status.controller.ts
  libs/shared/app-state/src/lib/online-status/online-status.event.ts
  libs/shared/app-state/src/lib/online-status/online-status.module.ts
  libs/shared/app-state/src/lib/online-status/online-status.requests.ts
  libs/shared/app-state/src/lib/online-status/online-status.service.ts
  libs/shared/app-state/src/lib/online-status/use-online-listener.ts
  libs/shared/app-state/src/lib/selectors/select-online-status.selector.ts
Labels: enhancement

#1892 [CP-2875] Add data-testid selector to "Show Connected Devices" button
  libs/core/__deprecated__/renderer/components/rest/menu/menu-bottom.component.tsx
  libs/core/__deprecated__/renderer/components/rest/menu/menu-group-test-ids.enum.ts
Labels: enhancement

#1867 [CP-2649][CP-2668][CP-2669] Integrate Alarm Application with Center - CRUD
  libs/core/files-manager/actions/get-files.action.ts
  libs/core/files-manager/actions/upload-file.action.ts
  libs/core/files-manager/components/manage-sounds-panel/manage-sounds-panel.component.tsx
  libs/core/files-manager/components/manage-sounds-storage-no-files/manage-sounds-storage-no-files.tsx
  libs/core/files-manager/components/manage-sounds.component.tsx
  libs/core/files-manager/constants/device-directory.constant.ts
  libs/core/files-manager/reducers/files-manager.interface.ts
  libs/core/files-manager/reducers/files-manager.reducer.ts
  libs/core/files-manager/selectors/get-directory-by-active-sound-app.selector.ts
Labels: QA, feature

#1885 [CP-2782] Data migration
  libs/core/__deprecated__/renderer/components/core/icon/icon-type.ts
  libs/core/__deprecated__/renderer/components/core/icon/icon.config.ts
  libs/core/__deprecated__/renderer/components/rest/menu/menu-bottom.component.tsx
  libs/core/__deprecated__/renderer/components/rest/menu/menu-group-test-ids.enum.ts
  libs/core/__deprecated__/renderer/constants/menu-elements.ts
  libs/core/__deprecated__/renderer/constants/urls.ts
  libs/core/__deprecated__/renderer/constants/views.ts
  libs/core/__deprecated__/renderer/locales/default/en-US.json
  libs/core/__deprecated__/renderer/store/reducers.ts
  libs/core/__deprecated__/renderer/wrappers/layout-desktop-wrapper.tsx
  libs/core/core/components/apps/base-app/base-app-routes.tsx
  libs/core/device-initialization/components/devices-initialization-modal-flows/api-device-initialization-modal-flow.tsx
  libs/core/modals-manager/components/connecting-loader-modal.component.tsx
  libs/generic-view/models/src/index.ts
  libs/generic-view/models/src/lib/form-checkbox-input.ts
  libs/generic-view/models/src/lib/mc-data-migration.ts
  libs/generic-view/store/src/index.ts
  libs/generic-view/store/src/lib/action-names.ts
  libs/generic-view/store/src/lib/data-migration/actions.ts
  libs/generic-view/store/src/lib/data-migration/clear-data-migration-device.action.ts
  libs/generic-view/store/src/lib/data-migration/reducer.ts
  libs/generic-view/store/src/lib/hooks/use-api-serial-port-listeners.ts
  libs/generic-view/store/src/lib/selectors/data-migration-devices.ts
  libs/generic-view/store/src/lib/selectors/data-migration-features.ts
  libs/generic-view/store/src/lib/selectors/index.ts
  libs/generic-view/theme/src/lib/color.ts
  libs/generic-view/theme/src/lib/radius.ts
  libs/generic-view/ui/src/index.ts
  libs/generic-view/ui/src/lib/icon/get-icon.helper.tsx
  libs/generic-view/ui/src/lib/icon/svg/data-migration.svg
  libs/generic-view/ui/src/lib/interactive/form/input/checkbox-input.tsx
  libs/generic-view/ui/src/lib/predefined/data-migration/arrow.svg
  libs/generic-view/ui/src/lib/predefined/data-migration/check.svg
  libs/generic-view/ui/src/lib/predefined/data-migration/components/device-card.tsx
  libs/generic-view/ui/src/lib/predefined/data-migration/components/device-selector.tsx
  libs/generic-view/ui/src/lib/predefined/data-migration/components/features-selector.tsx
  libs/generic-view/ui/src/lib/predefined/data-migration/components/source-selector.tsx
  libs/generic-view/ui/src/lib/predefined/data-migration/connection.svg
  libs/generic-view/ui/src/lib/predefined/data-migration/data-migration.tsx
  libs/generic-view/ui/src/lib/predefined/data-migration/dropdown.svg
  libs/generic-view/ui/src/lib/predefined/data-migration/instruction.tsx
  libs/generic-view/ui/src/lib/predefined/data-migration/target-selector.tsx
  libs/generic-view/ui/src/lib/predefined/data-migration/transfer-setup.tsx
  libs/generic-view/ui/src/lib/predefined/predefined.ts
  libs/generic-view/ui/src/lib/texts/headers.tsx
  libs/generic-view/ui/src/lib/texts/paragraphs.tsx
  libs/generic-view/utils/src/lib/generate-menu/generate-menu.ts
  libs/generic-view/utils/src/lib/models/icons.types.ts
  libs/shared/feature/.babelrc
  libs/shared/feature/.eslintrc.json
  libs/shared/feature/README.md
  libs/shared/feature/jest.config.ts
  libs/shared/feature/project.json
  libs/shared/feature/src/index.ts
  libs/shared/feature/src/lib/use-data-migration-device-selector.ts
  libs/shared/feature/tsconfig.json
  libs/shared/feature/tsconfig.lib.json
  libs/shared/feature/tsconfig.spec.json
  tsconfig.base.json
Labels: feature
