Repository mudita/mudita-center, pull requests merged in 2024-06, with the labels that each got.

#1879 [CP-2839] MDS Select your device copy and change in active indicator
  libs/core/__deprecated__/renderer/locales/default/en-US.json
  libs/core/device-select/components/drawer-device.component.tsx
Labels: feature

#1906 [CP-2789] Implement Workflow to build soft/force update application ready to use by automation
  .env.example
  .github/workflows/e2e-development.yml
  .github/workflows/e2e-feature-branch.yml
  .github/workflows/e2e-pre-production.yml
  .github/workflows/e2e-production.yml
  libs/core/settings/services/configuration.service.ts
  libs/e2e-mock/client/src/lib/e2e-mock-client.ts
  libs/e2e-mock/server/README.md
  libs/e2e-mock/server/src/index.ts
  libs/e2e-mock/server/src/lib/mock-http-state.service.ts
  libs/e2e-mock/server/src/lib/mock-updater-state.service.ts
  libs/e2e-mock/server/src/lib/server.tsx
  libs/electron/application-updater/src/lib/application-updater.module.ts
  libs/electron/application-updater/src/lib/mock-application-updater.service.ts
  libs/shared/http-client/.babelrc
  libs/shared/http-client/.eslintrc.json
  libs/shared/http-client/README.md
  libs/shared/http-client/jest.config.ts
  libs/shared/http-client/project.json
  libs/shared/http-client/src/index.ts
  libs/shared/http-client/src/lib/base-http-client.service.ts
  libs/shared/http-client/src/lib/http-client.factory.ts
  libs/shared/http-client/src/lib/http-client.service.ts
  libs/shared/http-client/src/lib/mock-http-client.service.ts
  libs/shared/http-client/tsconfig.json
  libs/shared/http-client/tsconfig.lib.json
  libs/shared/http-client/tsconfig.spec.json
  tsconfig.base.json
Labels: enhancement

#1912 [CP-2896] No files found after the next click on the Manage Sounds link
  apps/mudita-center-e2e/src/specs/news/news-check-online.e2e.ts
  libs/core/__deprecated__/renderer/components/core/button/button.styled.elements.tsx
  libs/core/__deprecated__/renderer/components/rest/menu/__snapshots__/menu.test.tsx.snap
Labels: bugfix, QA
